ci(gh-actions): skip CodeQL run for Dependabot branches on push events
This should resolve the following error:

Error: Workflows triggered by Dependabot on the "push" event run with read-only
access. Uploading Code Scanning results requires write access. To use Code
Scanning with Dependabot, please ensure you are using the "pull_request" event
for this workflow and avoid triggering on the "push" event for Dependabot
branches. See
https://docs.github.com/en/code-security/secure-coding/configuring-code-scanning#scanning-on-push
for more information on how to configure these events.

Credits: https://github.com/cisagov/con-pca-api/pull/224/commits/0d726beaa314e0229af0104fb082232eed1ef54f